### ISSUE TITLE
micropython on ESP32

### ISSUE THREAD

**Issue by Ansula1267** [ronschaeffer/sbm2mqtt#27]
Nice stuff! 
I have got it working on a RaspberryPi, with a few SwitchBot meters. One of the meters is on the verge of the BLE range. So I would like to deploy an additional 'receiver' and I would prefer an ESP32 for this (for cost and power consumption reasons). I have got MQTT working under microPython, but bluepy does not seem to be available here. Do you have suggestions how to proceed or maybe already have started working in that direction yourself?

**Comment by ronschaeffer** [comment]
Thanks, and sorry for the slow reply. I'm no longer maintaining this project, because the official Home Assistant Switchbot integration now supports meters, See https://www.home-assistant.io/integrations/switchbot/ if you haven't already.

You can do just what you're asking using a Bluetooth proxy in HA:  https://esphome.io/components/bluetooth_proxy.html
